baseurl: "/lukasTravelTheme" # the subpath of your site, e.g. /blog

paginate: 12
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled:
    - categories
  layout:
    category_archive

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
